# Generated by Django 2.1.9 on 2020-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_ID', models.CharField(max_length=100)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Category_Image', models.ImageField(upload_to='categoryimages/')),
            ],
            options={
                'db_table': 'PropertyCategoryData',
            },
        ),
    ]
