# Generated by Django 2.1.9 on 2020-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='Property_Address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydata',
            name='Property_Area',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydata',
            name='Property_Baths',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydata',
            name='Property_Beds',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydata',
            name='Property_Garages',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
