# Generated by Django 2.1.1 on 2020-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_account',
            name='agentpic',
            field=models.ImageField(upload_to='agentpic'),
        ),
    ]
