# Generated by Django 2.1.9 on 2020-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_ID', models.CharField(max_length=100)),
                ('Property_Name', models.CharField(max_length=100)),
                ('Property_About', models.CharField(max_length=1000)),
                ('Property_Price', models.CharField(max_length=50)),
                ('Property_Category', models.CharField(max_length=100)),
                ('Property_BuiltYear', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PropertyData',
            },
        ),
    ]
