# Generated by Django 2.1.1 on 2020-04-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0002_auto_20200410_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='myaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='pic')),
            ],
            options={
                'db_table': 'myaccount',
            },
        ),
    ]
