# Generated by Django 3.0.5 on 2020-04-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstateapp', '0002_auto_20200408_1609'),
        ('realstateapp', '0002_user_account'),
    ]

    operations = [
    ]
